// Generated by method-generator.js. DOT NOT MODIFY!！

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-analysis'] + '/MiddleService/services/QueryTemplateService?wsdl';

module.exports = function (req, res) {
	return {
		

			"addQueryTemplate": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "addQueryTemplate", args, callback, req, res);
			},
			

			"delQueryTemplate": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "delQueryTemplate", args, callback, req, res);
			},
			

			"getQueryCondition": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getQueryCondition", args, callback, req, res);
			},
			

			"getQueryTemplate": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getQueryTemplate", args, callback, req, res);
			},
			

			"updateQueryTemplate": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "updateQueryTemplate", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['app-analysis'] + '/MiddleService/services/QueryTemplateService?wsdl'
}
}