// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['dc-analysis'] + '/CloudPersonCoreProxyAgent/services/PersonCoreExternalQueryProxy?wsdl';

module.exports = function (req, res) {
	return {
		

			"checkExternalInfoExist": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "checkExternalInfoExist", args, callback, req, res);
			},
			

			"queryBorderInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryBorderInfo", args, callback, req, res);
			},
			

			"queryExternalCarInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryExternalCarInfo", args, callback, req, res);
			},
			

			"queryExternalInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryExternalInfo", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['dc-analysis'] + '/CloudPersonCoreProxyAgent/services/PersonCoreExternalQueryProxy?wsdl'
	}

}