// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['dc-analysis'] + '/PersonRelationExplore/services/PersonRelationExploreService?wsdl';

module.exports = function (req, res) {
	return {
		

			"analyzeEntityRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzeEntityRelation", args, callback, req, res);
			},
			

			"analyzeMultiEntitiesRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzeMultiEntitiesRelation", args, callback, req, res);
			},
			

			"analyzeMultiEntityRelationCustomed": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzeMultiEntityRelationCustomed", args, callback, req, res);
			},
			

			"analyzeMultiPeopleRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzeMultiPeopleRelation", args, callback, req, res);
			},
			

			"analyzePeopleRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzePeopleRelation", args, callback, req, res);
			},
			

			"analyzeTargetRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "analyzeTargetRelation", args, callback, req, res);
			},
			

			"comparePersonDocument": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "comparePersonDocument", args, callback, req, res);
			},
			

			"exploreEntityRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "exploreEntityRelation", args, callback, req, res);
			},
			

			"generatePersonRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "generatePersonRelation", args, callback, req, res);
			},
			

			"getRelationMetaData": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getRelationMetaData", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['dc-analysis'] + '/PersonRelationExplore/services/PersonRelationExploreService?wsdl'
	}

}