// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-common'] + '/CloudUtility/services/CommonPropertyService?wsdl';

module.exports = function (req, res) {
	return {
		

			"getCommonPropertiesByKey": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getCommonPropertiesByKey", args, callback, req, res);
			},
			

			"getCommonPropertiesByModule": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getCommonPropertiesByModule", args, callback, req, res);
			},
			

			"getConfigList": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getConfigList", args, callback, req, res);
			},
			

			"getSystemConfigValueByKey": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getSystemConfigValueByKey", args, callback, req, res);
			},
			

			"queryAllCommonProperties": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryAllCommonProperties", args, callback, req, res);
			},
			

			"updateConfigItems": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "updateConfigItems", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['app-common'] + '/CloudUtility/services/CommonPropertyService?wsdl'
	}

}