// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-common'] + '/CloudUtility/services/DirService?wsdl';

module.exports = function (req, res) {
	return {
		

			"addDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "addDir", args, callback, req, res);
			},
			

			"createUserWorkZone": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "createUserWorkZone", args, callback, req, res);
			},
			

			"delDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "delDir", args, callback, req, res);
			},
			

			"getDirTypeByDirId": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getDirTypeByDirId", args, callback, req, res);
			},
			

			"getSameNameDirId": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getSameNameDirId", args, callback, req, res);
			},
			

			"moveDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "moveDir", args, callback, req, res);
			},
			

			"queryDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryDir", args, callback, req, res);
			},
			

			"queryDirByDirType": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryDirByDirType", args, callback, req, res);
			},
			

			"updateDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "updateDir", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['app-common'] + '/CloudUtility/services/DirService?wsdl'
	}

}