// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-common'] + '/CloudWorkArea/services/WorkAreaService?wsdl';

module.exports = function (req, res) {
	return {
		

			"deleteResource": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "deleteResource", args, callback, req, res);
			},
			

			"getContainingDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getContainingDir", args, callback, req, res);
			},
			

			"getReportUrl": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getReportUrl", args, callback, req, res);
			},
			

			"getResourceByDirId": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getResourceByDirId", args, callback, req, res);
			},
			

			"getShareResourceInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getShareResourceInfo", args, callback, req, res);
			},
			

			"getWorkAreaDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getWorkAreaDir", args, callback, req, res);
			},
			

			"moveDir": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "moveDir", args, callback, req, res);
			},
			

			"queryPreference": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "queryPreference", args, callback, req, res);
			},
			

			"recordPreference": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "recordPreference", args, callback, req, res);
			},
			

			"renameResource": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "renameResource", args, callback, req, res);
			},
			

			"searchResource": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "searchResource", args, callback, req, res);
			},
			

			"shareResource": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "shareResource", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['app-common'] + '/CloudWorkArea/services/WorkAreaService?wsdl'
	}

}