// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('<%- appconfig %>');
var url = 'http://' + appConfig['<%- role %>'] + '<%- url %>';

module.exports = function (req, res) {
	return {
		<% methods.forEach(function (method) { %>

			"<%- method.name %>": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "<%- method.name %>", args, callback, req, res);
			},
			<% }) %>

		url: 'http://' + appConfig['<%- role %>'] + '<%- url %>'
	}

}