// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['dc-analysis'] + '/DI_WS/services/DataLinkService?wsdl';

module.exports = function (req, res) {
	return {
		

			"CloseConnection": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "CloseConnection", args, callback, req, res);
			},
			

			"CreateConnection": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "CreateConnection", args, callback, req, res);
			},
			

			"CreateTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "CreateTask", args, callback, req, res);
			},
			

			"GetAllConnection": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "GetAllConnection", args, callback, req, res);
			},
			

			"GetAllTaskByConnection": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "GetAllTaskByConnection", args, callback, req, res);
			},
			

			"GetConnectionByID": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "GetConnectionByID", args, callback, req, res);
			},
			

			"GetTaskStatus": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "GetTaskStatus", args, callback, req, res);
			},
			

			"ModifyConnection": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "ModifyConnection", args, callback, req, res);
			},
			

			"ModifyTaskState": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "ModifyTaskState", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['dc-analysis'] + '/DI_WS/services/DataLinkService?wsdl'
	}

}