// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['dc-analysis'] + '/UDP_WS/services/UdpSearchService?wsdl';

module.exports = function (req, res) {
	return {
		

			"getResultText": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getResultText", args, callback, req, res);
			},
			

			"getSearchItem": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getSearchItem", args, callback, req, res);
			},
			

			"getUdpSearchResult": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getUdpSearchResult", args, callback, req, res);
			},
			

			"searchWorkPlace": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "searchWorkPlace", args, callback, req, res);
			},
			

			"submitUdpSearchTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "submitUdpSearchTask", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['dc-analysis'] + '/UDP_WS/services/UdpSearchService?wsdl'
	}

}