// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['dc-analysis'] + '/CloudPersonCore/services/PersonCoreService?wsdl';

module.exports = function (req, res) {
	return {
		

			"batchGetPersonPhoto": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "batchGetPersonPhoto", args, callback, req, res);
			},
			

			"batchGetPersonSummary": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "batchGetPersonSummary", args, callback, req, res);
			},
			

			"checkEntityExist": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "checkEntityExist", args, callback, req, res);
			},
			

			"checkFaceQuality": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "checkFaceQuality", args, callback, req, res);
			},
			

			"generateDoc": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "generateDoc", args, callback, req, res);
			},
			

			"generatePersonDocument": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "generatePersonDocument", args, callback, req, res);
			},
			

			"getCondition": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getCondition", args, callback, req, res);
			},
			

			"getEntityName": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getEntityName", args, callback, req, res);
			},
			

			"getFaceRecogResult": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getFaceRecogResult", args, callback, req, res);
			},
			

			"getFaceRecogTaskID": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getFaceRecogTaskID", args, callback, req, res);
			},
			

			"getHujiAddressRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getHujiAddressRelation", args, callback, req, res);
			},
			

			"getImeiRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getImeiRelation", args, callback, req, res);
			},
			

			"getPCQueryResult": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPCQueryResult", args, callback, req, res);
			},
			

			"getPartner": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPartner", args, callback, req, res);
			},
			

			"getPartnerDetail": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPartnerDetail", args, callback, req, res);
			},
			

			"getPersonActionInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPersonActionInfo", args, callback, req, res);
			},
			

			"getPersonActionInfo": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPersonActionInfo", args, callback, req, res);
			},
			

			"getPersonDetail": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPersonDetail", args, callback, req, res);
			},
			

			"getPersonPhoto": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPersonPhoto", args, callback, req, res);
			},
			

			"getPhoneRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getPhoneRelation", args, callback, req, res);
			},
			

			"getQQ": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getQQ", args, callback, req, res);
			},
			

			"getQQGroup": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getQQGroup", args, callback, req, res);
			},
			

			"getRadiusRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getRadiusRelation", args, callback, req, res);
			},
			

			"getSocialRelation": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getSocialRelation", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['dc-analysis'] + '/CloudPersonCore/services/PersonCoreService?wsdl'
	}

}