// Generated by method-generator.js. DOT NOT MODIFY!£¡

var _ = require('underscore');
var path = require('path');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-common'] + ':8080/TaskManage/services/TaskManageService?wsdl';

module.exports = function (req, res) {
	return {
		

			"batchUpdateTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "batchUpdateTask", args, callback, req, res);
			},
			

			"countTasks": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "countTasks", args, callback, req, res);
			},
			

			"fetchTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "fetchTask", args, callback, req, res);
			},
			

			"getEquAimsetStatistics": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "getEquAimsetStatistics", args, callback, req, res);
			},
			

			"insertTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "insertTask", args, callback, req, res);
			},
			

			"operateTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "operateTask", args, callback, req, res);
			},
			

			"recheckTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "recheckTask", args, callback, req, res);
			},
			

			"resourceStatistics": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "resourceStatistics", args, callback, req, res);
			},
			

			"selectTasks": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "selectTasks", args, callback, req, res);
			},
			

			"taskStatistics": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "taskStatistics", args, callback, req, res);
			},
			

			"updateTask": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "updateTask", args, callback, req, res);
			},
			

			"updateTaskStatus": function (args, callback) {
				if (_.isFunction(args)) {
					callback = args;
					args = {};
				}
				return jws(url, "updateTaskStatus", args, callback, req, res);
			},
			

		url: 'http://' + appConfig['app-common'] + ':8080/TaskManage/services/TaskManageService?wsdl'
	}

}