// Generated by method-generator.js. DOT NOT MODIFY!！

var path = require('path');
var _ = require('underscore');
var jws = require(path.join(process.cwd(), 'utils/jws'));
var appConfig = require('../config.js');
var url = 'http://' + appConfig['app-analysis'] + '/RelationAnalysis/cxf/greetSoap?wsdl';

module.exports = function (req, res) {
	return {
		
		
		"initRelationAnalysisTask": function (args, callback) {
			if (_.isFunction(args)) {
				callback = args;
				args = {};
			}
			return jws(url, "initRelationAnalysisTask", args, callback, req, res);
		},
		
		
		"greetTest": function (args, callback) {
			if (_.isFunction(args)) {
				callback = args;
				args = {};
			}
			return jws(url, "greetTest", args, callback, req, res);
		},
		
		
		"getRelationAnalysisCacheStatus": function (args, callback) {
			if (_.isFunction(args)) {
				callback = args;
				args = {};
			}
			return jws(url, "getRelationAnalysisCacheStatus", args, callback, req, res);
		},
		

		url: 'http://' + appConfig['app-analysis'] + '/cxfexample/cxf/greetSoap?wsdl'
	}
}
